### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Topcliffe** [aaevan/Florida-Man-Headline-O-Matic#1]
Hi,

When I try to run this, I get a syntax error on the second quotation mark ("...then %s."...):

print "%s Florida man %s %s then %s." % (adjective, verb, subject, action)

Any idea what's going on?

Thanks,

MP

**Comment by aaevan** [comment]
I think I hadn't made it compatible with python 3-- should be fixed now.

**Comment by Topcliffe** [comment]
Cool, thanks!
MP

Date: Sun, 12 Jun 2016 21:05:23 -0700
